{% set name = "django-cities" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-cities-{{ version }}.tar.gz
  sha256: d84363acb060cfccd9b2aa57296dfee5eb85334b2c04f5b78deebf549752e2f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django-model-utils
    - python >=3.6
    - six
    - swapper
    - tqdm

test:
  imports:
    - cities
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/coderholic/django-cities
  summary: Place models and worldwide place data for Django
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
